# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- source

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run clean
  displayName: 'npm install and clean'

- script: 
    npm run generate
  displayName: 'generate hexo...'

- script: 
    cd ./public
    git init
    git add .
    git config user.name 'azure'
    git config user.email 'azure@auzre-pipelines'
    git commit -m 'ci'
    git log
    git push --force git@github.com:atomoo/atomoo.github.io.git HEAD:master
  displayName: 'deploy hexo'

